version: '3'

networks:
  plagiarism-checker:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:delegated
    depends_on:
      - php
      - mysql
    networks:
      - plagiarism-checker

  mysql:
    image: mysql:5.7.29
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - plagiarism-checker

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - .:/var/www/html:delegated
    ports:
      - "9000:9000"
    networks:
      - plagiarism-checker